NAME:-SHRIDATTA SHEKHAR BHASME
ROLL NO :- RBTL22CB072
SUBJECT:- MACHINE LEARNING
DATASET :- IRIS_DATASET

In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


In [ ]:
- `numpy` (np): Numerical Python - Library for numerical and matrix operations in Python.
- `pandas` (pd): Python Data Analysis Library - Library for data manipulation and analysis.
- `sklearn.model_selection` : Scikit-learn Model Selection - Library for model selection and evaluation.
- `sklearn.preprocessing` : Scikit-learn Preprocessing - Library for data preprocessing and feature scaling.
- `sklearn.metrics` : Scikit-learn Metrics - Library for evaluating the performance of machine learning models.

In [14]:
data=pd.read_csv(r"iris.csv")
data.head(n=5)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [16]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['variety'] = label_encoder.fit_transform(data['variety'])

In [17]:
train, test=train_test_split(data,random_state=42)
x_train=train[train.columns[2:30]]
y_train =train['variety']
x_test=test[test.columns[2:30]]
y_test =test['variety']

- `train, test=train_test_split(data,random_state=42)`:Splits the data into training and testing sets with
    a random state of 42 for reproducibility.
- `x_train=train[train.columns[2:30]]`: Extracts the features for the training set from columns 2 to 29.
- `y_train =train['variety']`: Extracts the target variable for the training set.
- `x_test=test[test.columns[2:30]]`: Extracts the features for the testing set from columns 2 to 29.
- `y_test =test['variety']`: Extracts the target variable for the testing set.

In [18]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [19]:
from sklearn.neural_network import MLPClassifier
MLP =MLPClassifier(hidden_layer_sizes=(10,10,10), max_iter=1000)
MLP.fit(x_train, y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

Artificial neural networks (ANNs) are biologically inspired computer programs designed to simulate the way in which the human brain processes information. ANNs gather their knowledge by detecting the patterns and relationships in data and learn (or are trained) through experience, not from programming.

In [20]:
predictions=MLP.predict(x_test)

In [21]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))


[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



A confusion matrix is a table used in machine learning and statistics to assess the performance of a classification model. It summarizes the results of classification by showing the counts of true positive, true negative, false positive, and false negative predictions.

In [22]:
print("Accuracy: ",accuracy_score(y_test,predictions))

Accuracy:  1.0


Conclusion:
The practical analysis of the Iris dataset using an Artificial Neural Network (ANN) model has yielded compelling results. With an achieved accuracy of 100%, the model has effectively learned and classified the different species of iris flowers, showcasing its ability to comprehend the intricate patterns within the dataset